### ISSUE TITLE
不能在服务器看视频

### ISSUE THREAD

**Issue by sankycui** [ossrs/srs-sea#16]
你好，我的手机是魅蓝 m1 metal，装好apk之后，apk运行正常，我推流到http://ossrs.net:8936/live/sea.flv，但是我点开Play the RTMP stream和 Play the FLV stream之后，开不到视频，点SRS测网速显示链接服务器失败，这个是怎么回事？谢谢！

**Comment by cyw3** [comment]
我也是这个问题。求解答。

**Comment by winlinvip** [comment]
Please use https://github.com/begeekmyfriend/yasea instead.
